/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';


export interface EntityModelGwbLinksT { 
    activeFlag?: string;
    createDate?: Date;
    createUserId?: string;
    displayName?: string;
    displayOrderNum?: number;
    id?: number;
    lastChangeDate?: Date;
    lastChangeUserId?: string;
    linkPath?: string;
    linkServer?: string;
    linkType?: string;
    links?: Links;
    name?: string;
    protocol?: string;
    updateStamp?: number;
}
