/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LinkRelation } from './linkRelation';


export interface Link { 
    deprecation?: string;
    href?: string;
    hreflang?: string;
    media?: string;
    name?: string;
    profile?: string;
    rel?: LinkRelation;
    title?: string;
    type?: string;
}
