/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FindPaylistCriteriaDto { 
    bmmCode?: string;
    cayCodes?: Array<string>;
    ccrCode?: string;
    councilMeetingDate?: string;
    docAbbreviation?: string;
    fy?: number;
    grantIc?: string;
    grantMech?: string;
    grantSerial?: string;
    grantSuffix?: string;
    grantType?: string;
    grantYear?: string;
    paylistStatusCode?: string;
    paylistType?: string;
}
