/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PaylistGrantsCriteriaDto { 
    activityCodes?: Array<string>;
    cayCodes?: Array<string>;
    councilMeetingDate?: string;
    docAbbreviation?: string;
    exceptionActivityCodes?: Array<string>;
    excludePaylistIds?: Array<number>;
    fy?: number;
    nonId?: number;
    primaryActivityCode?: string;
    rfaPaNumber?: string;
}
