openapi: 3.1.0
info:
  title: I2E IC Data Web Service API
  description: I2EICDWS Web Service
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: 1.0.0
servers:
  - url: http:/localhost/i2eicdws
    description: local
  - url: https://i2e-dev.nci.nih.gov/i2eicdws
    description: dev
  - url: https://i2e-test.nci.nih.gov/i2eicdws
    description: test
  - url: https://i2e-stage.nci.nih.gov/i2eicdws
    description: stage
  - url: https://i2e.nci.nih.gov/i2eicdws
    description: prod
paths:
  /api/v1/pcc-details/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: pccDetails
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /api/v1/main-pcc/assign/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: mainPccAssign
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
        - name: progClassCode
          in: query
          required: true
          schema:
            type: string
        - name: overWriteFlag
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /api/v1/icd-transaction/{transactionId}:
    post:
      tags:
        - ic-data-controller
      operationId: processTransaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/v1/ic-pcc/assign/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: icPccAssign
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: transactionType
          in: query
          required: true
          schema:
            type: string
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
        - name: oldPccCode
          in: query
          required: false
          schema:
            type: string
        - name: newPccCode
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /api/v1/ic-pcc/assign-merge/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: icPccAssignMerge
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: transactionType
          in: query
          required: true
          schema:
            type: string
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
        - name: oldPccCode
          in: query
          required: false
          schema:
            type: string
        - name: newPccCode
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /api/v1/fed-person-involvement/assign/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: fedPersonInvolvementAssign
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: transactionType
          in: query
          required: true
          schema:
            type: string
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
        - name: roleTypeCode
          in: query
          required: true
          schema:
            type: string
        - name: personId
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: versionCode
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /api/v1/awd-fundings/assign/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: awdFundingsAssign
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: transType
          in: query
          required: true
          schema:
            type: string
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
        - name: oldCan
          in: query
          required: false
          schema:
            type: string
        - name: newCan
          in: query
          required: false
          schema:
            type: string
        - name: newPcc
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /api/v1/appd-fundings/assign/{applId}:
    post:
      tags:
        - ic-data-controller
      operationId: appdFundinggsAssign
      parameters:
        - name: applId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: transType
          in: query
          required: true
          schema:
            type: string
        - name: phsOrgCode
          in: query
          required: true
          schema:
            type: string
        - name: totalPeriodAmt
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: directcostAmt
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: indirectcostAmt
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
components:
  schemas:
    Payload:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        businessErrorCode:
          type: string
        businessErrorMessage:
          type: string
