components:
  responses:
    BadRequest:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Invalid parameters or business error
    IcdProgClass:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ResponsesIcdProgClass'
      description: IC PCC Data
    UnauthorizedRequest:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/ApiError'
      description: Unauthorized Request error
  schemas:
    ApiError:
      description: Error details
      properties:
        businessErrorCode:
          type: integer
        businessErrorMessage:
          type: string
      type: object
    ApplIcdProgClassDetail:
      properties:
        asgnVersionCode:
          type: string
        icMainFlag:
          type: string
        progClassCode:
          type: string
      type: object
    ResponsesIcdProgClass:
      properties:
        applIcdProgClassDetails:
          items:
            $ref: '#/components/schemas/ApplIcdProgClassDetail'
          type: array
        applId:
          type: integer
        phsOrgCode:
          type: string
      type: object
info:
  description: A set of APIs used by IC Extension systems to update application specific
    information.
  title: IC Data API
  version: 1.0.0
openapi: 3.0.1
paths:
  /icdata/api/ice/appd-fundings/assign/{applId}:
    post:
      description: Assign IC appl period funding for an application. Converted from
        ice_dbms_appd_a_pkg. assign_proc stored procedure.
      operationId: assignApplPeriodFunding
      parameters:
      - description: ID of the target application.
        in: path
        name: applId
        required: true
        schema:
          type: integer
      - description: Transaction Type
        in: query
        name: transType
        required: true
        schema:
          type: string
      - description: Phs organization code
        in: query
        name: phsOrgCode
        required: true
        schema:
          type: string
      - description: Total Period Amount
        in: query
        name: totalPeriodAmt
        schema:
          type: integer
      - description: Direct Cost Amount
        in: query
        name: directCostAmt
        schema:
          type: integer
      - description: Indirect Cost Amount
        in: query
        name: indirectCostAmt
        schema:
          type: integer
      responses:
        '200':
          content: {}
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized Request error
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
      tags:
      - ICData Services Controller
  /icdata/api/ice/awd-fundings/assign/{applId}:
    post:
      description: Update tables in accordance with various business rules. Converted
        from ice_dbms_awfd_a_pkg.assign_proc stored procedure.
      operationId: assignAwardFunding
      parameters:
      - description: ID of the target application.
        in: path
        name: applId
        required: true
        schema:
          type: integer
      - description: Transaction Type
        in: query
        name: transType
        required: true
        schema:
          type: string
      - description: Phs organization code
        in: query
        name: phsOrgCode
        required: true
        schema:
          type: string
      - description: Old CAN
        in: query
        name: oldCan
        schema:
          type: string
      - description: New CAN
        in: query
        name: newCan
        schema:
          type: string
      - description: New Program Class Code
        in: query
        name: newPcc
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized Request error
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
      tags:
      - ICData Services Controller
  /icdata/api/ice/fed-person-involvement/assign/{applId}:
    post:
      description: Update Federal Person Involvement records for an application. Converted
        from ice_dbms_fedp_a_pkg.assign_proc stored procedure.
      operationId: assignFedPersonInvolvement
      parameters:
      - description: ID of the target application.
        in: path
        name: applId
        required: true
        schema:
          type: integer
      - description: Transaction type
        in: query
        name: transactionType
        required: true
        schema:
          type: string
      - description: Phs organization code
        in: query
        name: phsOrgCode
        required: true
        schema:
          type: string
      - description: Role type code
        in: query
        name: roleTypeCode
        required: true
        schema:
          type: string
      - description: Person ID
        in: query
        name: personId
        required: true
        schema:
          type: integer
      - description: Version code. Default value = 'M'.
        in: query
        name: versionCode
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized Request error
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
      tags:
      - ICData Services Controller
  /icdata/api/ice/ic-pcc/assign/{applId}:
    post:
      description: Assign IC involvement for an application. Converted from ice_dbms_icpcc_a_pkg.assign_ic_pcc_proc
        stored procedure.
      operationId: assignICInvolvement
      parameters:
      - description: ID of the target application.
        in: path
        name: applId
        required: true
        schema:
          type: integer
      - description: Transaction type
        in: query
        name: transactionType
        required: true
        schema:
          type: string
      - description: Phs organization code
        in: query
        name: phsOrgCode
        required: true
        schema:
          type: string
      - description: Old Program Class Code
        in: query
        name: oldPccCode
        schema:
          type: string
      - description: New Program Class Code
        in: query
        name: newPccCode
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized Request error
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
      tags:
      - ICData Services Controller
  /icdata/api/ice/main-pcc/assign/{applId}:
    post:
      description: Assign IC involvement for an application. Converted from ice_dbms_icpcc_a_pkg.assign_main_pcc_proc
        stored procedure.
      operationId: assignMainPccInvolvement
      parameters:
      - description: ID of the target application.
        in: path
        name: applId
        required: true
        schema:
          type: integer
      - description: Phs organization code
        in: query
        name: phsOrgCode
        required: true
        schema:
          type: string
      - description: Program Class Code
        in: query
        name: progClassCode
        required: true
        schema:
          type: string
      - description: Overwrite Flag. Default value "Y"
        in: query
        name: overWriteFlag
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized Request error
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
      tags:
      - ICData Services Controller
  /icdata/api/ice/pcc-details/{applId}:
    get:
      description: Fetch IC-PCC details for an application.
      operationId: getPcc
      parameters:
      - description: ID of the target application.
        in: path
        name: applId
        required: true
        schema:
          type: integer
      - description: Phs organization code
        in: query
        name: phsOrgCode
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsesIcdProgClass'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Unauthorized Request error
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
          description: Invalid parameters or business error
      tags:
      - ICData Services Controller
servers:
- description: development
  url: https://services.internal.dev.era.nih.gov
- description: test
  url: https://services.internal.test.era.nih.gov
- description: staging
  url: https://services.internal.era.stage.nih.gov
- description: production
  url: https://services.internal.era.nih.gov
tags:
- description: ICData REST Controller
  name: icdata-services-controller
x-original-swagger-version: '2.0'
