/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RoAssignmentControllerService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getActiveROList
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getActiveROListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getActiveROListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getActiveROListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getActiveROListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/v1/ro-list/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getDefaultRO
     * 
     * @param isDefaultRO isDefaultRO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDefaultROUsingGET(isDefaultRO: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getDefaultROUsingGET(isDefaultRO: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getDefaultROUsingGET(isDefaultRO: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getDefaultROUsingGET(isDefaultRO: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (isDefaultRO === null || isDefaultRO === undefined) {
            throw new Error('Required parameter isDefaultRO was null or undefined when calling getDefaultROUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/v1/ro-assignment-rules/${encodeURIComponent(String(isDefaultRO))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRoAssignmentRulesList
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRoAssignmentRulesListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getRoAssignmentRulesListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getRoAssignmentRulesListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getRoAssignmentRulesListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/v1/ro-assignment-rules/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inactivateAllRoAssignments
     * 
     * @param roNpeId roNpeId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inactivateAllRoAssignmentsUsingPATCH(roNpeId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public inactivateAllRoAssignmentsUsingPATCH(roNpeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public inactivateAllRoAssignmentsUsingPATCH(roNpeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public inactivateAllRoAssignmentsUsingPATCH(roNpeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (roNpeId === null || roNpeId === undefined) {
            throw new Error('Required parameter roNpeId was null or undefined when calling inactivateAllRoAssignmentsUsingPATCH.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (roNpeId !== undefined && roNpeId !== null) {
            queryParameters = queryParameters.set('roNpeId', <any>roNpeId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.patch<any>(`${this.basePath}/api/v1/ro-assignment-rules/`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveOrUpdateDefaultRo
     * 
     * @param defaultRoNpeId defaultRoNpeId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveOrUpdateDefaultRoUsingPUT(defaultRoNpeId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public saveOrUpdateDefaultRoUsingPUT(defaultRoNpeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public saveOrUpdateDefaultRoUsingPUT(defaultRoNpeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public saveOrUpdateDefaultRoUsingPUT(defaultRoNpeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (defaultRoNpeId === null || defaultRoNpeId === undefined) {
            throw new Error('Required parameter defaultRoNpeId was null or undefined when calling saveOrUpdateDefaultRoUsingPUT.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (defaultRoNpeId !== undefined && defaultRoNpeId !== null) {
            queryParameters = queryParameters.set('defaultRoNpeId', <any>defaultRoNpeId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<any>(`${this.basePath}/api/v1/ro-assignment-rules/`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveRoAssignment
     * 
     * @param npeId npeId
     * @param userId userId
     * @param mechList mechList[]
     * @param rfaList rfaList[]
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveRoAssignmentUsingPUT(npeId: string, userId: string, mechList?: Array<string>, rfaList?: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public saveRoAssignmentUsingPUT(npeId: string, userId: string, mechList?: Array<string>, rfaList?: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public saveRoAssignmentUsingPUT(npeId: string, userId: string, mechList?: Array<string>, rfaList?: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public saveRoAssignmentUsingPUT(npeId: string, userId: string, mechList?: Array<string>, rfaList?: Array<string>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (npeId === null || npeId === undefined) {
            throw new Error('Required parameter npeId was null or undefined when calling saveRoAssignmentUsingPUT.');
        }

        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling saveRoAssignmentUsingPUT.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (mechList) {
            mechList.forEach((element) => {
                queryParameters = queryParameters.append('mechList[]', <any>element);
            })
        }
        if (rfaList) {
            rfaList.forEach((element) => {
                queryParameters = queryParameters.append('rfaList[]', <any>element);
            })
        }
        if (userId !== undefined && userId !== null) {
            queryParameters = queryParameters.set('userId', <any>userId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'application/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<any>(`${this.basePath}/api/v1/ro-assignments/${encodeURIComponent(String(npeId))}`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
